apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  annotations:
    dapr.io/app-id: admin-frontend
    dapr.io/app-port: '80'
    dapr.io/enable-metrics: 'true'
    dapr.io/enabled: 'true'
    dapr.io/metrics-port: '9099'
    dapr.io/sidecar-listen-addresses: 0.0.0.0
    #dapr.io/config: ingress-apisix-config
spec:
  selector:
    matchLabels:
      app: admin-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: docker.io/darksuei/admin-frontend-upi-v3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001

