apiVersion: apps/v1
kind: Deployment
metadata:
  name: moja-switch
  namespace: microservices
  labels:
    app: moja-switch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moja-switch
  template:
    metadata:
      labels:
        app: moja-switch
      annotations:
        dapr.io/app-id: "moja-switch"
        dapr.io/app-port: '3001'
        dapr.io/enable-metrics: 'true'
        dapr.io/enabled: 'true'
        dapr.io/metrics-port: '9099'
        dapr.io/sidecar-listen-addresses: 0.0.0.0
    spec:
      containers:
      - name: moja-switch
        image: docker.io/darksuei/mojaloop-switch-upi-v3.7
        #image: docker.io/darksuei/mojaloop-switch-beta:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: LOG_PATH
          value: "./logs"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_DISABLED
          value: "false"
        - name: JWT_SECRET
          value: "a4572f12e96b981b71d247d3d2467d6984450a1363daa60f3825786b5d9ee540"
        - name: JWT_EXPIRES_IN
          value: "1d"
        - name: DB_USERNAME
          value: "doadmin"
        - name: DB_PASSWORD
          value: "AVNS_W46qm467C_cWTsVrsOB"
        - name: DB_DATABASE
          value: "moja_switch"
        - name: DB_PORT
          value: "25060"
        - name: DB_DATABASE_TYPE
          value: "postgres"
        - name: DB_HOST
          value: "mojaloop-db-do-user-10555812-0.c.db.ondigitalocean.com"
        - name: ACCOUNT_SERVICE_URL
          value: "http://206.189.252.227/api/v1"
        - name: MOJALOOP_SWITCH_URL
          value: "http://206.189.252.227/switch/api/v1"
        - name: HASH_SECRET
          value: "65e45925bed8f54c4380d064ffce4fa6"
        - name: HASH_IV
          value: "65e45925bed8f54c4380d064ffce4fa6"
        - name: DEFAULT_DFSP_ID
          value: "001"
        - name: HOST
          value: "0.0.0.0"
        - name: DAPR_HTTP_PORT
          value: "3500"
