apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
spec:
  selector:
    matchLabels:
      app: checkout-service
  replicas: 1
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
        - name: checkout-service
          image: docker.io/darksuei/checkout-frontend-upi-v3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000