apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  http:
    - name: {{ .Values.app.name }}
      match:
        hosts:
          - {{ .Values.apisix.host }}
        paths:
          - {{ .Values.apisix.path }}
      backends:
        - serviceName: {{ .Values.app.name }}
          servicePort: {{ .Values.app.port }}
